import { useEffect, useRef, useState } from "react";
import { projectAudio } from "../../../services/projectAudioService";
import { audioAssetUrl } from "../../../services/contentNarrationService";
const button = "rounded-lg border border-sky-400/40 px-3 py-2 text-sm text-sky-100 disabled:opacity-50";
const input = "mt-1 w-full rounded-lg border border-border bg-theme p-2 text-sm";
const name = a => a.metadata?.originalName || a.id;
const duration = a => `${Number(a.durationSeconds).toFixed(2)} s`;
export function AudioMixProductionView({ project, state, draft, busy, loading, error, notice, metadata, onMetadata, onDraft, onSave, onUpload }) {
  const music = state.assets.filter(a => a.metadata?.audioRole === "BACKGROUND_MUSIC"), sounds = state.assets.filter(a => a.metadata?.audioRole === "SOUND_EFFECT");
  const selected = music.find(a => a.id === draft?.backgroundMusicAssetId);
  const dirty = draft && JSON.stringify(draft) !== JSON.stringify(state.settings);
  const change = patch => onDraft({ ...draft, ...patch });
  const editEffect = (id, patch) => change({ effects: draft.effects.map(e => e.id === id ? { ...e, ...patch } : e) });
  const upload = (role, title) => <label className={`${button} cursor-pointer`}>{title}<input aria-label={title} type="file" accept=".mp3,.wav,audio/mpeg,audio/wav,audio/x-wav" disabled={busy || loading} className="sr-only" onChange={e => { const file = e.target.files?.[0]; if (file) onUpload(role, file); e.target.value = ""; }} /></label>;
  return <section aria-label="Música e efeitos sonoros" className="space-y-4 rounded-2xl border border-border bg-card p-5">
    <h2 className="text-xl font-semibold">Música de fundo e efeitos sonoros</h2>
    <p className="text-sm text-muted-foreground">O preview toca cada arquivo isoladamente. Gere uma nova versão do vídeo para ouvir a mixagem completa.</p>
    {loading && <p role="status">Carregando configuração de áudio…</p>}{error && <p role="alert" className="text-sm text-red-200">{error}</p>}{notice && <p role="status" className="text-sm text-sky-200">{notice}</p>}
    <details><summary className="cursor-pointer text-sm">Origem e licença dos próximos uploads</summary><div className="mt-3 grid gap-3 sm:grid-cols-2">{[["origin", "Origem"], ["license", "Licença informada"], ["notes", "Observações"]].map(([key, label]) => <label key={key}>{label}<input aria-label={label} maxLength={key === "notes" ? 1000 : 300} className={input} value={metadata[key]} onChange={e => onMetadata({ ...metadata, [key]: e.target.value })} /></label>)}</div><p className="mt-2 text-xs text-muted-foreground">As informações são fornecidas por você; o upload não comprova autorização de uso.</p></details>
    <div className="flex flex-wrap gap-2">{upload("BACKGROUND_MUSIC", "Enviar música")}{upload("SOUND_EFFECT", "Enviar efeito sonoro")}</div>
    <p className="text-xs text-muted-foreground">MP3 ou WAV PCM · Até 20 MB e 10 minutos por arquivo. Música e efeitos são opcionais.</p>
    {draft && <><h3 className="font-semibold">Música de fundo</h3><label>Música selecionada<select aria-label="Música selecionada" className={input} value={draft.backgroundMusicAssetId ?? ""} disabled={busy} onChange={e => change({ backgroundMusicAssetId: e.target.value || null })}><option value="">Sem música</option>{music.map(a => <option key={a.id} value={a.id}>{name(a)} · {duration(a)}</option>)}</select></label>
      {selected && <div className="space-y-2"><audio aria-label="Preview da música" controls preload="metadata" src={audioAssetUrl(selected)} className="w-full" /><p className="text-xs text-muted-foreground">{selected.metadata.origin || "Upload do usuário"} · Licença: {selected.metadata.license || "Não informada"}{selected.metadata.notes ? ` · ${selected.metadata.notes}` : ""}</p><button className={button} disabled={busy} onClick={() => change({ backgroundMusicAssetId: null })}>Remover música</button></div>}
      <div className="grid gap-3 sm:grid-cols-3"><label>Volume da música · {Math.round(draft.musicVolume * 100)}%<input aria-label="Volume da música" type="range" min="0" max="0.5" step="0.01" value={draft.musicVolume} disabled={busy} className="mt-2 w-full accent-sky-400" onChange={e => change({ musicVolume: Number(e.target.value) })} /></label>{[["musicFadeInSeconds", "Fade-in"], ["musicFadeOutSeconds", "Fade-out"]].map(([key, label]) => <label key={key}>{label} · segundos<input aria-label={label} type="number" min="0" max="30" step="0.1" className={input} disabled={busy} value={draft[key]} onChange={e => change({ [key]: Number(e.target.value) })} /></label>)}</div>
      <p className="text-xs text-muted-foreground">O percentual ajusta ganho relativo; o volume percebido depende do arquivo. A narração permanece a fonte principal.</p>
      <div className="flex flex-wrap gap-4">{[["loopMusic", "Repetir música até o fim do vídeo"], ["duckingEnabled", "Reduzir música durante narração"]].map(([key, label]) => <label key={key} className="text-sm"><input type="checkbox" checked={draft[key]} disabled={busy} onChange={e => change({ [key]: e.target.checked })} /> {label}</label>)}</div>
      <h3 className="font-semibold">Efeitos sonoros</h3>
      {sounds.length > 0 && <details><summary className="cursor-pointer text-sm">Arquivos de efeitos enviados</summary><div className="mt-2 space-y-3">{sounds.map(a => <div key={a.id}><p className="text-sm">{name(a)} · {duration(a)}</p><audio aria-label={`Preview do efeito ${name(a)}`} controls preload="none" src={audioAssetUrl(a)} className="w-full" /><p className="text-xs text-muted-foreground">Licença: {a.metadata.license || "Não informada"}</p></div>)}</div></details>}
      {project.scenes.slice().sort((a, b) => a.order - b.order).map(scene => <article key={scene.id} className="space-y-3 rounded-lg border border-border p-3"><h4 className="font-medium">Cena {scene.order} · Efeitos</h4>{draft.effects.filter(e => e.sceneId === scene.id).map(effect => <div key={effect.id} className="grid gap-3 rounded-lg border border-border p-3 sm:grid-cols-3"><label>Arquivo<select aria-label={`Arquivo do efeito ${effect.id}`} className={input} disabled={busy} value={effect.assetId} onChange={e => editEffect(effect.id, { assetId: e.target.value })}>{sounds.map(a => <option key={a.id} value={a.id}>{name(a)}</option>)}</select></label><label>Início na cena · segundos<input aria-label={`Offset do efeito ${effect.id}`} type="number" min="0" step="0.1" className={input} value={effect.startOffsetSeconds} disabled={busy} onChange={e => editEffect(effect.id, { startOffsetSeconds: Number(e.target.value) })} /></label><label>Volume · {Math.round(effect.volume * 100)}%<input aria-label={`Volume do efeito ${effect.id}`} type="range" min="0" max="1" step="0.01" className="mt-2 w-full accent-sky-400" value={effect.volume} disabled={busy} onChange={e => editEffect(effect.id, { volume: Number(e.target.value) })} /></label><label className="text-sm"><input type="checkbox" checked={effect.enabled} disabled={busy} onChange={e => editEffect(effect.id, { enabled: e.target.checked })} /> Ativo</label><button className={button} disabled={busy} onClick={() => change({ effects: draft.effects.filter(e => e.id !== effect.id) })}>Remover efeito</button></div>)}<button className={button} disabled={busy || !sounds.length || draft.effects.length >= 32 || draft.effects.filter(e => e.sceneId === scene.id).length >= 8} onClick={() => change({ effects: [...draft.effects, { id: crypto.randomUUID(), sceneId: scene.id, assetId: sounds[0].id, startOffsetSeconds: 0, volume: 0.25, enabled: true, scope: "SCENE" }] })}>Adicionar efeito na cena {scene.order}</button><p className="text-xs text-muted-foreground">Offset relativo ao início real da cena. O efeito termina no fim da cena.</p></article>)}
      {draft.effects.some(e => !project.scenes.some(s => s.id === e.sceneId)) && <div role="alert" className="text-amber-200">Há efeitos em cenas removidas. <button className="underline" disabled={busy} onClick={() => change({ effects: draft.effects.filter(e => project.scenes.some(s => s.id === e.sceneId)) })}>Remover efeitos das cenas antigas</button></div>}
      <button className={button} disabled={busy || loading || !dirty} onClick={onSave}>{busy ? "Processando áudio…" : "Salvar mixagem"}</button>{dirty && <p className="text-sm text-amber-200">Salve a mixagem antes de gerar o vídeo. As versões anteriores serão preservadas.</p>}
    </>}
  </section>;
}
export function AudioMixProduction({ project, onProjectChange, onDirtyChange }) {
  const [state, setState] = useState({ assets: [], settings: null }), [draft, setDraft] = useState(null), [busy, setBusy] = useState(false), [error, setError] = useState(""), [notice, setNotice] = useState(""), [loading, setLoading] = useState(true), [metadata, setMetadata] = useState({ origin: "Upload do usuário", license: "", notes: "" });
  const inFlight = useRef(false);
  const dirty = Boolean(draft && JSON.stringify(draft) !== JSON.stringify(state.settings));
  useEffect(() => { onDirtyChange?.(dirty); }, [dirty, onDirtyChange]);
  useEffect(() => { let active = true; projectAudio.get(project.id).then(result => { if (active) { setState(result); setDraft(result.settings); setError(""); } }).catch(e => { if (active) setError(e.message); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [project.id]);
  async function run(work, save = false) {
    if (inFlight.current) return; inFlight.current = true; setBusy(true); setError(""); setNotice("");
    try { const result = await work(); setState(result); if (save) { setDraft(result.settings); onProjectChange?.(result.project); setNotice("Mixagem salva. Gere uma nova versão do vídeo para aplicar."); } else setNotice("Áudio enviado. Selecione e salve para usar no vídeo."); }
    catch (e) { setError(e.message); } finally { inFlight.current = false; setBusy(false); }
  }
  return <AudioMixProductionView project={project} state={state} draft={draft} busy={busy} loading={loading} error={error} notice={notice} metadata={metadata} onMetadata={setMetadata} onDraft={setDraft} onSave={() => void run(() => projectAudio.save(project, draft), true)} onUpload={(role, file) => void run(() => projectAudio.upload(project, role, file, metadata))} />;
}
